# Generated by Django 6.0.1 on 2026-01-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('estudiantes', '0002_remove_estudiante_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tokenregistry',
            name='token_regis_user_id_eb3717_idx',
        ),
        migrations.AddIndex(
            model_name='tokenregistry',
            index=models.Index(fields=['estudiante', 'is_active'], name='token_regis_estudia_65ac66_idx'),
        ),
        migrations.RemoveField(
            model_name='tokenregistry',
            name='user',
        ),
    ]
