# Generated by Django 6.0.1 on 2026-01-09 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('es_estado_activo', models.BooleanField(default=True, help_text='Activo, Baja temporal, Baja definitiva, Egresado')),
            ],
            options={
                'verbose_name': 'Estado de Estudiante',
                'verbose_name_plural': 'Estados de Estudiante',
                'db_table': 'estados_estudiante',
            },
        ),
        migrations.CreateModel(
            name='Estrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='A, B, C, D, etc.', max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento: 0.00 a 100.00', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estrato',
                'verbose_name_plural': 'Estratos',
                'db_table': 'estratos',
                'indexes': [models.Index(fields=['activo'], name='idx_estrato_activo')],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'grados',
                'indexes': [models.Index(fields=['nombre', 'nivel'], name='idx_grado_nombre_nivel')],
                'unique_together': {('nombre', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('generacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(db_column='grado_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.grado')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('hash_contrasena', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10, message='La contraseña debe tener al menos 10 caracteres')])),
                ('digest_llave', models.CharField(blank=True, help_text='Hash adicional para autenticación', max_length=64, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.grupo')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_efectiva', models.DateTimeField(help_text='Fecha en que entra en vigor el estado')),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que realizó el cambio', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estadoestudiante')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'historial_estados_estudiante',
                'ordering': ['-fecha_efectiva'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstratoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_efectiva', models.DateTimeField(help_text='Fecha en que entra en vigor el estrato')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estrato', models.ForeignKey(db_column='estrato_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estrato')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Historial de Estrato',
                'verbose_name_plural': 'Historial de Estratos',
                'db_table': 'historial_estratos_estudiante',
                'ordering': ['-fecha_efectiva'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por_estudiante', models.ForeignKey(blank=True, db_column='actualizado_por_estudiante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores_actualizados', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutores',
            },
        ),
        migrations.CreateModel(
            name='EstudianteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(help_text='Padre, Madre, Abuelo, Tutor Legal, etc.', max_length=100)),
                ('responsable_pagos', models.BooleanField(default=False)),
                ('recibe_notificaciones', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Para dar de baja sin eliminar')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('tutor', models.ForeignKey(db_column='tutor_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.tutor')),
            ],
            options={
                'verbose_name': 'Estudiante-Tutor',
                'verbose_name_plural': 'Estudiantes-Tutores',
                'db_table': 'estudiantes_tutores',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionSocioeconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_vivienda', models.CharField(help_text='Propia, Rentada, Familiar, etc.', max_length=255)),
                ('miembros_hogar', models.IntegerField(help_text='Número de personas en el hogar')),
                ('documentos_json', models.TextField(help_text='JSON con URLs/paths de documentos probatorios')),
                ('evaluado_por', models.CharField(blank=True, help_text='Usuario que realizó la evaluación', max_length=255, null=True)),
                ('aprobado', models.BooleanField(blank=True, help_text='null=pendiente, true=aprobado, false=rechazado', null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('estrato_sugerido', models.ForeignKey(db_column='estrato_sugerido_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estrato')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Evaluación Socioeconómica',
                'verbose_name_plural': 'Evaluaciones Socioeconómicas',
                'db_table': 'evaluaciones_socioeconomicas',
                'indexes': [models.Index(fields=['estudiante'], name='idx_evalsocio_estudiante'), models.Index(fields=['estrato_sugerido'], name='idx_evalsocio_estrato'), models.Index(fields=['fecha_evaluacion'], name='idx_evalsocio_fecha'), models.Index(fields=['aprobado'], name='idx_evalsocio_aprobado')],
            },
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['grado'], name='idx_grupo_grado'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('nombre', 'generacion', 'grado')},
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['matricula'], name='idx_estudiante_matricula'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['nombre_usuario'], name='idx_estudiante_usuario'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['grupo'], name='idx_estudiante_grupo'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='idx_estudiante_nombre_completo'),
        ),
        migrations.AddIndex(
            model_name='historialestadosestudiante',
            index=models.Index(fields=['estudiante'], name='idx_historialestado_estudiante'),
        ),
        migrations.AddIndex(
            model_name='historialestadosestudiante',
            index=models.Index(fields=['estado'], name='idx_historialestado_estado'),
        ),
        migrations.AddIndex(
            model_name='historialestadosestudiante',
            index=models.Index(fields=['fecha_efectiva'], name='idx_historialestado_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialestadosestudiante',
            index=models.Index(fields=['estudiante', 'fecha_efectiva'], name='idx_estudiante_estado_temporal'),
        ),
        migrations.AddIndex(
            model_name='historialestratoestudiante',
            index=models.Index(fields=['estudiante'], name='idx_historialestrato_estudiante'),
        ),
        migrations.AddIndex(
            model_name='historialestratoestudiante',
            index=models.Index(fields=['estrato'], name='idx_historialestrato_estrato'),
        ),
        migrations.AddIndex(
            model_name='historialestratoestudiante',
            index=models.Index(fields=['fecha_efectiva'], name='idx_historialestrato_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialestratoestudiante',
            index=models.Index(fields=['estudiante', 'fecha_efectiva'], name='idx_estudiante_estrato_temporal'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['correo'], name='idx_tutor_correo'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['telefono'], name='idx_tutor_telefono'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['ultima_actualizacion'], name='idx_tutor_ultima_actualizacion'),
        ),
        migrations.AddIndex(
            model_name='estudiantetutor',
            index=models.Index(fields=['estudiante'], name='idx_estudiantetutor_estudiante'),
        ),
        migrations.AddIndex(
            model_name='estudiantetutor',
            index=models.Index(fields=['tutor'], name='idx_estudiantetutor_tutor'),
        ),
        migrations.AddIndex(
            model_name='estudiantetutor',
            index=models.Index(fields=['responsable_pagos'], name='idx_responsable_pagos'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiantetutor',
            unique_together={('estudiante', 'tutor')},
        ),
    ]
