# Generated by Django 6.0.1 on 2026-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('es_estado_activo', models.BooleanField(default=True, help_text='Activo, Baja temporal, Baja definitiva, Egresado')),
            ],
            options={
                'verbose_name': 'Estado de Estudiante',
                'verbose_name_plural': 'Estados de Estudiante',
                'db_table': 'estados_estudiante',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='EstudianteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(help_text='Padre, Madre, Abuelo, Tutor Legal, etc.', max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Para dar de baja sin eliminar')),
            ],
            options={
                'verbose_name': 'Estudiante-Tutor',
                'verbose_name_plural': 'Estudiantes-Tutores',
                'db_table': 'estudiantes_tutores',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionSocioeconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_vivienda', models.CharField(help_text='Propia, Rentada, Familiar, etc.', max_length=255)),
                ('miembros_hogar', models.IntegerField(help_text='Número de personas en el hogar')),
                ('documentos_json', models.TextField(help_text='JSON con URLs/paths de documentos probatorios')),
                ('aprobado', models.BooleanField(blank=True, help_text='null=pendiente, true=aprobado, false=rechazado', null=True)),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Evaluación Socioeconómica',
                'verbose_name_plural': 'Evaluaciones Socioeconómicas',
                'db_table': 'evaluaciones_socioeconomicas',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'grados',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('generacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'historial_estados_estudiante',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=17)),
                ('correo', models.EmailField(max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutores',
            },
        ),
        migrations.CreateModel(
            name='Estrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='A, B, C, D, etc.', max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento: 0.00 a 100.00', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estrato',
                'verbose_name_plural': 'Estratos',
                'db_table': 'estratos',
                'indexes': [models.Index(fields=['activo'], name='idx_estrato_activo')],
            },
        ),
    ]
