# Generated by Django 5.1.15 on 2026-01-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estratohistorial',
            name='estrato',
        ),
        migrations.RemoveField(
            model_name='evaluacionsocioeconomica',
            name='estrato_sugerido',
        ),
        migrations.RemoveField(
            model_name='estratohistorial',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='estudiantetutor',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='evaluacionsocioeconomica',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiantetutor',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='grado',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='nivel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentstatus',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='studentstatus',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='apellido_materno',
            new_name='maternal_surname',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='apellido_paterno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='nombre',
            new_name='paternal_surname',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameModel(
            old_name='Grado',
            new_name='Grade',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('paternal_surname', models.CharField(max_length=255)),
                ('maternal_surname', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.group')),
            ],
        ),
        migrations.CreateModel(
            name='StratumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('stratum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.stratum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.student')),
            ],
        ),
        migrations.CreateModel(
            name='SocioeconomicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing_type', models.CharField(max_length=255)),
                ('number_of_members', models.IntegerField()),
                ('documents', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('suggested_stratum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.stratum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.student')),
            ],
        ),
        migrations.RenameModel(
            old_name='EstadoEstudiante',
            new_name='StudentStatus',
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.studentstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('is_payment_responsible', models.BooleanField(default=False)),
                ('receives_notifications', models.BooleanField(default=True)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.tutor')),
            ],
        ),
        migrations.DeleteModel(
            name='EstadoEstudianteHistorial',
        ),
        migrations.DeleteModel(
            name='Estrato',
        ),
        migrations.DeleteModel(
            name='EstratoHistorial',
        ),
    ]
