# Generated by Django 6.0.1 on 2026-01-11 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiantetutor',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_matricula', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='estrato',
            field=models.ForeignKey(blank=True, db_column='estrato_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='estudiantes.estrato'),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_matricula', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddIndex(
            model_name='grado',
            index=models.Index(fields=['nombre', 'nivel'], name='idx_grado_nombre_nivel'),
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together={('nombre', 'nivel')},
        ),
        migrations.AddField(
            model_name='grupo',
            name='grado',
            field=models.ForeignKey(db_column='grado_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.grado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.grupo'),
        ),
        migrations.AddField(
            model_name='historialestadosestudiante',
            name='estado',
            field=models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estadoestudiante'),
        ),
        migrations.AddField(
            model_name='historialestadosestudiante',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_matricula', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['correo'], name='idx_tutor_correo'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['telefono'], name='idx_tutor_telefono'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['ultima_actualizacion'], name='idx_tutor_ultima_actualizacion'),
        ),
        migrations.AddField(
            model_name='estudiantetutor',
            name='tutor',
            field=models.ForeignKey(db_column='tutor_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.tutor'),
        ),
        migrations.AddIndex(
            model_name='evaluacionsocioeconomica',
            index=models.Index(fields=['estudiante'], name='idx_evalsocio_estudiante'),
        ),
        migrations.AddIndex(
            model_name='evaluacionsocioeconomica',
            index=models.Index(fields=['fecha_evaluacion'], name='idx_evalsocio_fecha'),
        ),
        migrations.AddIndex(
            model_name='evaluacionsocioeconomica',
            index=models.Index(fields=['aprobado'], name='idx_evalsocio_aprobado'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['grado'], name='idx_grupo_grado'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('nombre', 'generacion', 'grado')},
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['matricula'], name='idx_estudiante_matricula'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['grupo'], name='idx_estudiante_grupo'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='idx_estudiante_nombre_completo'),
        ),
        migrations.AddIndex(
            model_name='historialestadosestudiante',
            index=models.Index(fields=['estudiante'], name='idx_historialestado_estudiante'),
        ),
        migrations.AddIndex(
            model_name='historialestadosestudiante',
            index=models.Index(fields=['estado'], name='idx_historialestado_estado'),
        ),
        migrations.AddIndex(
            model_name='estudiantetutor',
            index=models.Index(fields=['estudiante'], name='idx_estudiantetutor_estudiante'),
        ),
        migrations.AddIndex(
            model_name='estudiantetutor',
            index=models.Index(fields=['tutor'], name='idx_estudiantetutor_tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiantetutor',
            unique_together={('estudiante', 'tutor')},
        ),
    ]
