# Generated by Django 5.1.15 on 2026-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_student_user_student_key_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password123', max_length=36),
        ),
    ]
