# Generated by Django 6.0.1 on 2026-01-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tutor',
            name='idx_tutor_ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='ultima_actualizacion',
        ),
    ]
