# Generated by Django 5.1.15 on 2026-01-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0003_cafeteriaattendance_student_delete_asistenciacomedor'),
        ('estudiantes', '0002_stratum_remove_estratohistorial_estrato_and_more'),
        ('pagos', '0002_paymentconcept_remove_adeudo_concepto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='EvaluacionSocioeconomica',
        ),
        migrations.DeleteModel(
            name='EstudianteTutor',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
