# Generated by Django 6.0.1 on 2026-01-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_remove_tutor_idx_tutor_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='updateable',
            field=models.BooleanField(default=True),
        ),
    ]
