# Generated by Django 6.0.1 on 2026-01-09 03:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_student_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socioeconomicevaluation',
            options={'verbose_name': 'Evaluación Socioeconómica', 'verbose_name_plural': 'Evaluaciones Socioeconómicas'},
        ),
        migrations.AlterModelOptions(
            name='stratum',
            options={'verbose_name': 'Estrato', 'verbose_name_plural': 'Estratos'},
        ),
        migrations.AlterModelOptions(
            name='stratumhistory',
            options={'verbose_name': 'Historial de Estratos', 'verbose_name_plural': 'Historiales de Estratos'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='studentstatus',
            options={'verbose_name': 'Estatus', 'verbose_name_plural': 'Estatus'},
        ),
        migrations.AlterModelOptions(
            name='studentstatushistory',
            options={'verbose_name': 'Historial Estatus', 'verbose_name_plural': 'Historial Estatus'},
        ),
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.studentstatus', verbose_name='Estado actual'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_stratum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.stratum', verbose_name='Estrato actual'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=155, validators=[django.core.validators.MinLengthValidator(10, message='Field must be at least 10 characters long')]),
        ),
    ]
