# Generated by Django 6.0.1 on 2026-01-18 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_estudiante_updateable'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrato',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Color hex para dashboards ej: #FF5733', max_length=7),
        ),
        migrations.AddField(
            model_name='estrato',
            name='ingreso_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso mensual máximo para este estrato', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estrato',
            name='ingreso_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso mensual mínimo para este estrato', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='alergias_alimentarias',
            field=models.TextField(blank=True, help_text='Alergias alimentarias del estudiante', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='comentarios_comision',
            field=models.TextField(blank=True, help_text='Comentarios de la comisión al aprobar/rechazar', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='es_reconsideracion',
            field=models.BooleanField(default=False, help_text='True si es solicitud de reconsideración con nueva documentación'),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='estrato_sugerido',
            field=models.ForeignKey(blank=True, help_text='Estrato calculado automáticamente por el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_sugeridas', to='estudiantes.estrato'),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite para revalidación anual', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='justificacion_estrato',
            field=models.TextField(blank=True, help_text='Explicación de por qué se asignó este estrato', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='notificacion_enviada',
            field=models.BooleanField(default=False, help_text='True si ya se notificó al padre/tutor'),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='requiere_aprobacion_especial',
            field=models.BooleanField(default=False, help_text='True si el cambio de estrato es mayor a 2 niveles'),
        ),
        migrations.AddField(
            model_name='historialestadosestudiante',
            name='es_baja_temporal',
            field=models.BooleanField(blank=True, help_text='True=temporal, False=definitiva, null=no es baja', null=True),
        ),
        migrations.AddField(
            model_name='historialestadosestudiante',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha efectiva de la baja', null=True),
        ),
    ]
