# Generated by Django 6.0.1 on 2026-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_estrato_color_estrato_ingreso_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='porcentaje_beca',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de beca asignado (0.00 a 100.00)', max_digits=5),
        ),
    ]
