# Generated by Django 6.0.1 on 2026-01-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_estudiante_porcentaje_beca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento de la beca (0.00 a 100.00)', max_digits=5)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de vigencia de la beca')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la beca')),
                ('valida', models.BooleanField(default=True, help_text='Indica si la beca está vigente. Se cambia a False cuando vence.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
                'db_table': 'becas',
                'indexes': [models.Index(fields=['valida'], name='idx_beca_valida'), models.Index(fields=['fecha_vencimiento'], name='idx_beca_vencimiento')],
            },
        ),
        migrations.CreateModel(
            name='BecaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, help_text='Fecha en que se retiró la beca. Null si sigue activa.', null=True)),
                ('activa', models.BooleanField(default=True, help_text='True si la beca sigue asignada al estudiante')),
                ('motivo_retiro', models.TextField(blank=True, help_text='Motivo por el cual se retiró la beca', null=True)),
                ('asignado_por', models.CharField(blank=True, help_text='Usuario que asignó la beca', max_length=255, null=True)),
                ('beca', models.ForeignKey(db_column='beca_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.beca')),
                ('estudiante', models.ForeignKey(db_column='estudiante_matricula', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Beca-Estudiante',
                'verbose_name_plural': 'Becas-Estudiantes',
                'db_table': 'becas_estudiantes',
                'indexes': [models.Index(fields=['beca'], name='idx_becaestudiante_beca'), models.Index(fields=['estudiante'], name='idx_becaestudiante_estudiante'), models.Index(fields=['activa'], name='idx_becaestudiante_activa')],
            },
        ),
    ]
