# Generated by Django 6.0.1 on 2026-01-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_beca_becaestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 2024-2025', max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False, help_text='Solo un ciclo debe estar activo a la vez')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciclo Escolar',
                'verbose_name_plural': 'Ciclos Escolares',
                'db_table': 'ciclos_escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado (Aprobado)'), ('reprobado', 'Reprobado'), ('baja_temporal', 'Baja Temporal'), ('baja_definitiva', 'Baja Definitiva'), ('egresado', 'Egresado de Nivel'), ('pendiente_pago', 'Pendiente de Pago/Reinscripción'), ('pendiente_asignacion', 'Pagado - Pendiente Asignación Grupo')], default='activo', max_length=50)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promedio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.IntegerField(help_text='1=Preescolar, 2=Primaria, 3=Secundaria')),
                ('grados_totales', models.IntegerField(help_text='Cuántos grados tiene este nivel (ej: 3, 6)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'niveles_educativos',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['orden_global'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grado',
            name='numero_grado',
            field=models.IntegerField(default=1, help_text='Grado relativo al nivel (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='grado',
            name='orden_global',
            field=models.IntegerField(default=0, help_text='Orden secuencial absoluto (1=1°Prees, 12=3°Sec)'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='capacidad_maxima',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.CharField(help_text='DEPRECATED: Usar nivel_educativo', max_length=100),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='generacion',
            field=models.CharField(help_text='DEPRECATED: Usar ciclo_escolar. Ejemplo: 2024-2025', max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(help_text='A, B, C', max_length=100),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ciclo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='estudiantes.cicloescolar'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['ciclo_escolar'], name='idx_grupo_ciclo'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='ciclo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='estudiantes.cicloescolar'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='estudiantes.grupo'),
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grados', to='estudiantes.niveleducativo'),
        ),
        migrations.AddIndex(
            model_name='grado',
            index=models.Index(fields=['orden_global'], name='idx_grado_orden_global'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['estudiante'], name='idx_inscripcion_estudiante'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['ciclo_escolar'], name='idx_inscripcion_ciclo'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['estatus'], name='idx_inscripcion_estatus'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'ciclo_escolar')},
        ),
    ]
