# Generated by Django 6.0.1 on 2026-01-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_cicloescolar_inscripcion_niveleducativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='orden_global',
            field=models.IntegerField(default=0, help_text='Orden secuencial absoluto (1=1°Prees, ..., 12=3°Sec)'),
        ),
    ]
