# Generated by Django 6.0.1 on 2026-02-01 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_grado_orden_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(blank=True, help_text='CURP del estudiante', max_length=18, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escuela_procedencia',
            field=models.CharField(blank=True, help_text='Escuela de procedencia del estudiante', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del estudiante', null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto predeterminado (del tutor principal)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionsocioeconomica',
            name='porcentaje_descuento_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento del estrato al momento de la evaluación', max_digits=5, null=True),
        ),
    ]
