# Generated by Django 6.0.1 on 2026-02-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_estudiante_curp_estudiante_escuela_procedencia_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='estudiante',
            name='idx_estudiante_grupo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo',
        ),
    ]
