# Generated by Django 6.0.1 on 2026-02-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_remove_estudiante_idx_estudiante_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inscripcion',
            name='idx_inscripcion_ciclo',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'grupo')},
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='ciclo_escolar',
        ),
    ]
