# Generated by Django 6.0.1 on 2026-02-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_remove_inscripcion_idx_inscripcion_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantetutor',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Indica si este es el tutor principal para trámites y pagos'),
        ),
    ]
