# Generated by Django 6.0.1 on 2026-02-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiantetutor_es_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(limit_choices_to={'ciclo_escolar__activo': True}, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='estudiantes.grupo'),
        ),
    ]
