# Generated by Django 6.0.2 on 2026-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_alter_inscripcion_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curp_hash',
            field=models.CharField(blank=True, help_text='Hash del CURP para búsquedas', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(blank=True, help_text='CURP del estudiante (Encriptado)', max_length=255, null=True, unique=True),
        ),
    ]
