# Generated by Django 6.0.1 on 2026-02-06 22:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0012_remove_inscripcion_idx_inscripcion_ciclo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administradores_escolares', to='estudiantes.niveleducativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin_escolar_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administradores_escolares',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_maestro', to='estudiantes.cicloescolar')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_maestro', to='estudiantes.grupo')),
            ],
            options={
                'db_table': 'asignaciones_maestro',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('puede_modificar', models.BooleanField(default=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('asignacion_maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='academico.asignacionmaestro')),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_autorizadas', to='academico.administradorescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_periodo', to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='AutorizacionCambioCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('utilizada', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_dadas', to='academico.administradorescolar')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='academico.calificacion')),
            ],
            options={
                'db_table': 'autorizaciones_cambio_calificacion',
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maestros', to='estudiantes.niveleducativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maestro_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maestros',
            },
        ),
        migrations.AddField(
            model_name='calificacion',
            name='capturada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_capturadas', to='academico.maestro'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='modificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_modificadas', to='academico.maestro'),
        ),
        migrations.AddField(
            model_name='asignacionmaestro',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='academico.maestro'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='estudiantes.grado')),
            ],
            options={
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='CalificacionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificaciones_periodos', models.JSONField()),
                ('calificacion_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estatus', models.CharField(choices=[('AO', 'Aprobado Ordinario'), ('RP', 'Reprobado')], max_length=2)),
                ('modificacion_manual', models.BooleanField(default=False)),
                ('calificacion_recursamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_finales', to='estudiantes.cicloescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_finales', to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_finales', to='academico.materia')),
            ],
            options={
                'db_table': 'calificaciones_finales',
            },
        ),
        migrations.AddField(
            model_name='asignacionmaestro',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='academico.materia'),
        ),
        migrations.CreateModel(
            name='ModificacionManualCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('motivo', models.TextField()),
                ('estatus_anterior', models.CharField(max_length=2)),
                ('estatus_nuevo', models.CharField(max_length=2)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_manuales_admin', to='academico.calificacion')),
                ('calificacion_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_manuales', to='academico.calificacionfinal')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones_manuales_realizadas', to='academico.administradorescolar')),
            ],
            options={
                'db_table': 'modificaciones_manuales_calificaciones',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio_captura', models.DateField(editable=False)),
                ('fecha_fin_captura', models.DateField(editable=False)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_evaluacion', to='estudiantes.cicloescolar')),
            ],
            options={
                'db_table': 'periodos_evaluacion',
            },
        ),
        migrations.AddField(
            model_name='calificacion',
            name='periodo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='academico.periodoevaluacion'),
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('numero_periodos_evaluacion', models.IntegerField(help_text='3 o 4 períodos por ciclo', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(4)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_educativos', to='estudiantes.niveleducativo')),
            ],
            options={
                'db_table': 'programas_educativos',
            },
        ),
        migrations.AddField(
            model_name='periodoevaluacion',
            name='programa_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_evaluacion', to='academico.programaeducativo'),
        ),
        migrations.AddField(
            model_name='materia',
            name='programa_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='academico.programaeducativo'),
        ),
        migrations.AddIndex(
            model_name='administradorescolar',
            index=models.Index(fields=['usuario'], name='idx_adminesc_usuario'),
        ),
        migrations.AddIndex(
            model_name='administradorescolar',
            index=models.Index(fields=['nivel_educativo'], name='idx_adminesc_nivel'),
        ),
        migrations.AddIndex(
            model_name='administradorescolar',
            index=models.Index(fields=['activo'], name='idx_adminesc_activo'),
        ),
        migrations.AddIndex(
            model_name='autorizacioncambiocalificacion',
            index=models.Index(fields=['calificacion'], name='idx_autcalif_calificacion'),
        ),
        migrations.AddIndex(
            model_name='autorizacioncambiocalificacion',
            index=models.Index(fields=['autorizado_por'], name='idx_autcalif_admin'),
        ),
        migrations.AddIndex(
            model_name='autorizacioncambiocalificacion',
            index=models.Index(fields=['utilizada'], name='idx_autcalif_utilizada'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['usuario'], name='idx_maestro_usuario'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['nivel_educativo'], name='idx_maestro_nivel'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['activo'], name='idx_maestro_activo'),
        ),
        migrations.AddIndex(
            model_name='calificacionfinal',
            index=models.Index(fields=['estudiante'], name='idx_calfinal_estudiante'),
        ),
        migrations.AddIndex(
            model_name='calificacionfinal',
            index=models.Index(fields=['materia'], name='idx_calfinal_materia'),
        ),
        migrations.AddIndex(
            model_name='calificacionfinal',
            index=models.Index(fields=['ciclo_escolar'], name='idx_calfinal_ciclo'),
        ),
        migrations.AddIndex(
            model_name='calificacionfinal',
            index=models.Index(fields=['estatus'], name='idx_calfinal_estatus'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionfinal',
            unique_together={('estudiante', 'materia', 'ciclo_escolar')},
        ),
        migrations.AddIndex(
            model_name='asignacionmaestro',
            index=models.Index(fields=['maestro'], name='idx_asignacion_maestro'),
        ),
        migrations.AddIndex(
            model_name='asignacionmaestro',
            index=models.Index(fields=['grupo'], name='idx_asignacion_grupo'),
        ),
        migrations.AddIndex(
            model_name='asignacionmaestro',
            index=models.Index(fields=['materia'], name='idx_asignacion_materia'),
        ),
        migrations.AddIndex(
            model_name='asignacionmaestro',
            index=models.Index(fields=['ciclo_escolar'], name='idx_asignacion_ciclo'),
        ),
        migrations.AddIndex(
            model_name='asignacionmaestro',
            index=models.Index(fields=['activa'], name='idx_asignacion_activa'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionmaestro',
            unique_together={('grupo', 'materia', 'ciclo_escolar')},
        ),
        migrations.AddIndex(
            model_name='modificacionmanualcalificacion',
            index=models.Index(fields=['calificacion_final'], name='idx_modman_calfinal'),
        ),
        migrations.AddIndex(
            model_name='modificacionmanualcalificacion',
            index=models.Index(fields=['calificacion'], name='idx_modman_calif'),
        ),
        migrations.AddIndex(
            model_name='modificacionmanualcalificacion',
            index=models.Index(fields=['modificado_por'], name='idx_modman_admin'),
        ),
        migrations.AddIndex(
            model_name='modificacionmanualcalificacion',
            index=models.Index(fields=['fecha_modificacion'], name='idx_modman_fecha'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estudiante'], name='idx_calif_estudiante'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['asignacion_maestro'], name='idx_calif_asignacion'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['periodo_evaluacion'], name='idx_calif_periodo'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha_captura'], name='idx_calif_captura'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('estudiante', 'asignacion_maestro', 'periodo_evaluacion')},
        ),
        migrations.AddIndex(
            model_name='programaeducativo',
            index=models.Index(fields=['nivel_educativo'], name='idx_programa_nivel'),
        ),
        migrations.AddIndex(
            model_name='programaeducativo',
            index=models.Index(fields=['activo'], name='idx_programa_activo'),
        ),
        migrations.AddIndex(
            model_name='periodoevaluacion',
            index=models.Index(fields=['ciclo_escolar'], name='idx_periodo_ciclo'),
        ),
        migrations.AddIndex(
            model_name='periodoevaluacion',
            index=models.Index(fields=['programa_educativo'], name='idx_periodo_programa'),
        ),
        migrations.AddIndex(
            model_name='periodoevaluacion',
            index=models.Index(fields=['estatus'], name='idx_periodo_estatus'),
        ),
        migrations.AlterUniqueTogether(
            name='periodoevaluacion',
            unique_together={('ciclo_escolar', 'programa_educativo', 'numero_periodo')},
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['grado'], name='idx_materia_grado'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['programa_educativo'], name='idx_materia_programa'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['activa'], name='idx_materia_activa'),
        ),
    ]
