# Generated by Django 6.0.1 on 2026-02-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='fecha_inicio',
        ),
    ]
