# Generated by Django 6.0.1 on 2026-02-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_remove_maestro_email_remove_materia_fecha_fin_and_more'),
        ('estudiantes', '0013_estudiantetutor_es_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('FESTIVO', 'Día Festivo'), ('EVALUACION', 'Periodo de Evaluación'), ('EVENTO', 'Evento Escolar'), ('PAGO', 'Fecha Límite de Pago'), ('OTRO', 'Otro')], default='EVENTO', max_length=20)),
                ('color', models.CharField(default='#3b82f6', help_text='Color en formato hexadecimal', max_length=7)),
                ('es_global', models.BooleanField(default=True)),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='estudiantes.niveleducativo')),
            ],
            options={
                'db_table': 'eventos_calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
