# Generated by Django 6.0.1 on 2026-02-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_eventocalendario'),
        ('estudiantes', '0014_alter_inscripcion_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradorescolar',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administradores_escolares', to='estudiantes.niveleducativo'),
        ),
        migrations.AlterField(
            model_name='asignacionmaestro',
            name='grupo',
            field=models.ForeignKey(limit_choices_to={'ciclo_escolar__activo': True}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_maestro', to='estudiantes.grupo'),
        ),
    ]
