# Generated by Django 6.0.1 on 2026-02-21 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_administradorescolar_nivel_educativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='academico.calificacion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='academico.maestro')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to='academico.administradorescolar')),
            ],
            options={
                'db_table': 'solicitudes_cambio_calificacion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
