# Generated by Django 6.0.2 on 2026-02-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_solicitudcambiocalificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
