# Generated by Django 6.0.2 on 2026-02-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_eventocalendario_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='es_recurrente',
            field=models.BooleanField(default=False, help_text='¿Se repite anualmente (mismo mes y día)?'),
        ),
    ]
