# Generated by Django 6.0.1 on 2026-01-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login_attempts',
                'indexes': [models.Index(fields=['email', 'timestamp'], name='idx_login_email_time'), models.Index(fields=['ip_address', 'timestamp'], name='idx_login_ip_time')],
            },
        ),
    ]
