# Generated by Django 6.0.1 on 2026-02-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador TI'), ('becas_admin', 'Administrador de Becas'), ('finanzas_admin', 'Administrador de Finanzas'), ('comedor_admin', 'Administrador de Comedor'), ('admisiones_admin', 'Administrador de Admisiones'), ('contador', 'Contador'), ('cafeteria', 'Cafetería'), ('bibliotecario', 'Bibliotecario')], default='estudiante', max_length=20),
        ),
    ]
