# Generated by Django 6.0.1 on 2026-02-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador TI'), ('becas_admin', 'Administrador de Becas'), ('finanzas_admin', 'Administrador de Finanzas'), ('comedor_admin', 'Administrador de Comedor'), ('admisiones_admin', 'Administrador de Admisiones'), ('maestro', 'Maestro'), ('admin_escolar', 'Administrador Escolar'), ('bibliotecario', 'Administrador de Biblioteca')], default='estudiante', max_length=20),
        ),
    ]
