# Generated by Django 6.0.1 on 2026-01-21 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_paterno', models.CharField(max_length=20, null=True)),
                ('apellido_materno', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutor_temp',
                'indexes': [models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='idx_tutoradmision_nombre_completo')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionUser',
            fields=[
                ('folio', models.IntegerField(default=2000, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios_aspirantes',
                'indexes': [models.Index(fields=['folio'], name='idx_aspirante_folio')],
            },
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_paterno', models.CharField(max_length=20, null=True)),
                ('apellido_materno', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.admissionuser')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
                'db_table': 'aspirantes',
            },
        ),
        migrations.CreateModel(
            name='AdmissionTutorAspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(help_text='Padre, Madre, Abuelo, Tutor Legal, etc.', max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(db_column='tutor_id', on_delete=django.db.models.deletion.CASCADE, to='admissions.admissiontutor')),
                ('aspirante', models.ForeignKey(db_column='aspirante_folio', on_delete=django.db.models.deletion.CASCADE, to='admissions.aspirante')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Aspirantes-Tutores',
                'db_table': 'aspirante_tutor',
            },
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='idx_aspirante_nombre_completo'),
        ),
        migrations.AddIndex(
            model_name='admissiontutoraspirante',
            index=models.Index(fields=['aspirante'], name='idx_aspirantetutor'),
        ),
        migrations.AddIndex(
            model_name='admissiontutoraspirante',
            index=models.Index(fields=['tutor'], name='idx_tutoraspirante'),
        ),
        migrations.AlterUniqueTogether(
            name='admissiontutoraspirante',
            unique_together={('aspirante', 'tutor')},
        ),
    ]
