# Generated by Django 6.0.1 on 2026-01-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admissiontutor',
            new_name='idx_tutoradm_nombre_completo',
            old_name='idx_tutoradmision_nombre_completo',
        ),
    ]
