# Generated by Django 6.0.1 on 2026-01-22 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_rename_idx_tutoradmision_nombre_completo_idx_tutoradm_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 11, 30, 29, 700134)),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='metodo_pago',
            field=models.CharField(help_text='Efectivo, Tarjeta, Transferencia, Cheque', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='numero_referencia',
            field=models.CharField(blank=True, help_text='Número de referencia bancaria', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='recibido_por',
            field=models.CharField(blank=True, help_text='Usuario que registró el pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='ruta_recibo',
            field=models.TextField(blank=True, help_text='Ruta al comprobante de pago', null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
