# Generated by Django 6.0.1 on 2026-01-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_aspirante_fecha_pago_aspirante_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'verification_codes',
            },
        ),
        migrations.AlterModelOptions(
            name='admissiontutoraspirante',
            options={'verbose_name': 'Tutor de Aspirante', 'verbose_name_plural': 'Aspirantes-Tutores'},
        ),
        migrations.RemoveIndex(
            model_name='admissiontutoraspirante',
            name='idx_aspirantetutor',
        ),
        migrations.RemoveIndex(
            model_name='admissiontutoraspirante',
            name='idx_tutoraspirante',
        ),
        migrations.RemoveIndex(
            model_name='aspirante',
            name='idx_aspirante_nombre_completo',
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='aceptacion_reglamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='acta_nacimiento_check',
            field=models.BooleanField(default=False, help_text='¿Entregó/Subió Acta?'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='autorizacion_imagen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='aspirantes/docs/'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='curp',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='curp_check',
            field=models.BooleanField(default=False, help_text='¿Entregó/Subió CURP?'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='escuela_procedencia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='fase_actual',
            field=models.IntegerField(default=1, help_text='1:Datos, 2:Socio, 3:Docs, 4:Pago, 5:Fin'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='ingreso_mensual_familiar',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='internet_encasa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='miembros_hogar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='ocupacion_madre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='pagado_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='promedio_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='tipo_vivienda',
            field=models.CharField(help_text='Propia, Rentada, Prestada', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='vehiculos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='admissiontutor',
            name='apellido_materno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissiontutor',
            name='apellido_paterno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissiontutor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissiontutor',
            name='numero_telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admissiontutoraspirante',
            name='aspirante',
            field=models.ForeignKey(db_column='aspirante_id', on_delete=django.db.models.deletion.CASCADE, to='admissions.aspirante'),
        ),
        migrations.AlterField(
            model_name='admissionuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='admissionuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='apellido_materno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='apellido_paterno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='metodo_pago',
            field=models.CharField(blank=True, help_text='Efectivo, Tarjeta, Transferencia, Cheque', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='ruta_recibo',
            field=models.TextField(blank=True, help_text='Ruta al comprobante (si aplica)', null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='status',
            field=models.CharField(default='pendiente', help_text='pendiente, aprobado, rechazado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='admissionuser',
            index=models.Index(fields=['email'], name='idx_aspirante_email'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['curp'], name='idx_aspirante_curp'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['fase_actual'], name='idx_aspirante_fase'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['email', 'code'], name='idx_verification_email_code'),
        ),
    ]
