# Generated by Django 6.0.1 on 2026-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_verificationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionuser',
            name='folio',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
