# Generated by Django 6.0.1 on 2026-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_admissionuser_folio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspirante',
            old_name='genero',
            new_name='sexo',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='acta_nacimiento_estudiante',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/actas/'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='acta_nacimiento_tutor',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/actas_tutores/'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='curp_pdf',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/curp/'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='curp_tutor_pdf',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/curp_tutores/'),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='data_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='acta_nacimiento_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='admissions/documents/domicilio/'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='curp_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='status',
            field=models.CharField(choices=[('ASPIRANTE', 'Aspirante'), ('ACEPTADO', 'Aceptado'), ('NO_ACEPTADO', 'No Aceptado')], default='ASPIRANTE', max_length=20),
        ),
    ]
