# Generated by Django 6.0.1 on 2026-01-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_rename_genero_aspirante_sexo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionuser',
            options={'verbose_name': 'Usuario Aspirante', 'verbose_name_plural': 'Usuarios Aspirantes'},
        ),
        migrations.AddField(
            model_name='admissionuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='admissiontutoraspirante',
            name='parentesco',
            field=models.CharField(help_text='Padre, madre, Abuelo, Tutor Legal, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='ruta_recibo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
