# Generated by Django 6.0.1 on 2026-01-27 02:07

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_admissiontutor_acta_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontutor',
            name='acta_nacimiento',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AlterField(
            model_name='admissiontutor',
            name='curp_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='acta_nacimiento_estudiante',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='acta_nacimiento_tutor',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='curp_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='curp_tutor_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
    ]
