# Generated by Django 6.0.1 on 2026-01-27 04:00

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_alter_admissiontutor_acta_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiontutor',
            name='carta_bajo_protesta',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='carta_ingresos',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='comprobante_ingresos',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='contrato_arrendamiento_predial',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='foto_fachada_domicilio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='ine_tutor',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.tutor_upload_path),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='acta_nacimiento',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='boleta_ciclo_actual',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='boleta_ciclo_anterior',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='foto_credencial',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
    ]
