# Generated by Django 6.0.1 on 2026-01-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_admissiontutor_carta_bajo_protesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='comentarios_analisis',
            field=models.TextField(blank=True, help_text='Comentarios del análisis de solicitud', null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='comentarios_comite',
            field=models.TextField(blank=True, help_text='Comentarios del comité de admisiones', null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='fecha_entrevista_psicologia',
            field=models.DateField(blank=True, help_text='Fecha de la entrevista de psicología', null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='fecha_examen_pedagogico',
            field=models.DateField(blank=True, help_text='Fecha de aplicación de exámenes pedagógicos', null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='fecha_visita_domiciliaria',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la visita domiciliaria', null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='status',
            field=models.CharField(choices=[('ASPIRANTE', 'Aspirante'), ('ACEPTADO', 'Aceptado'), ('NO_ACEPTADO', 'No Aceptado'), ('RECHAZADO', 'Rechazado')], default='ASPIRANTE', max_length=20),
        ),
    ]
