# Generated by Django 6.0.1 on 2026-01-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_aspirante_comentarios_analisis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='nivel_ingreso',
            field=models.CharField(blank=True, choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=20, null=True),
        ),
    ]
