# Generated by Django 6.0.1 on 2026-02-17 22:19

import admissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_aspirante_nivel_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiontutor',
            name='foto_fachada_domicilio',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='foto_fachada_domicilio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=admissions.models.aspirante_upload_path),
        ),
    ]
