# Generated by Django 6.0.2 on 2026-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_remove_admissiontutor_foto_fachada_domicilio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='boleta_ciclo_actual',
        ),
        migrations.AddField(
            model_name='admissiontutor',
            name='curp_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='curp_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admissiontutor',
            name='curp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='curp',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
