# Generated by Django 6.0.1 on 2026-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('tipo_comida', models.CharField(help_text='Desayuno, Comida, Cena', max_length=100)),
                ('precio_aplicado', models.DecimalField(decimal_places=2, help_text='Precio aplicado con descuento ya calculado', max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asistencia de Cafetería',
                'verbose_name_plural': 'Asistencias de Cafetería',
                'db_table': 'asistencia_cafeteria',
            },
        ),
    ]
