# Generated by Django 6.0.1 on 2026-01-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comedor', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciacafeteria',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddIndex(
            model_name='asistenciacafeteria',
            index=models.Index(fields=['estudiante'], name='idx_cafeteria_estudiante'),
        ),
        migrations.AddIndex(
            model_name='asistenciacafeteria',
            index=models.Index(fields=['fecha_asistencia'], name='idx_cafeteria_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciacafeteria',
            unique_together={('estudiante', 'fecha_asistencia', 'tipo_comida')},
        ),
    ]
