# Generated by Django 5.1.15 on 2026-01-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0002_cafeteriaattendance_and_more'),
        ('estudiantes', '0002_stratum_remove_estratohistorial_estrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriaattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.student'),
        ),
        migrations.DeleteModel(
            name='AsistenciaComedor',
        ),
    ]
