# Generated by Django 6.0.1 on 2026-01-16 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Nombre de la comida', max_length=160)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio', max_digits=10)),
                ('desactivar', models.BooleanField(default=False, help_text='Al desactivar este elemento del menu, ya no saldrá más')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menú',
                'db_table': 'Menu',
            },
        ),
        migrations.AddField(
            model_name='asistenciacafeteria',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='comedor.menu'),
        ),
    ]
