# Generated by Django 6.0.1 on 2026-01-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0003_menu_asistenciacafeteria_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Fecha de inicio de la semana')),
                ('semana_fin', models.DateField(help_text='Fecha de fin de la semana')),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF del menu', upload_to='menus/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion breve del menu', max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menu Semanal',
                'verbose_name_plural': 'Menus Semanales',
                'db_table': 'menus_semanales',
                'ordering': ['-semana_inicio'],
            },
        ),
    ]
