# Generated by Django 6.0.1 on 2026-01-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0004_menusemanal'),
        ('estudiantes', '0009_alter_grado_orden_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeudoComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('recargo_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.asistenciacafeteria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Adeudo de Comedor',
                'verbose_name_plural': 'Adeudos de Comedor',
                'db_table': 'adeudos_comedor',
                'indexes': [models.Index(fields=['estudiante'], name='idx_adeudo_comedor_est'), models.Index(fields=['pagado'], name='idx_adeudo_comedor_pagado')],
            },
        ),
    ]
