# Generated by Django 6.0.1 on 2026-01-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0005_adeudocomedor'),
        ('pagos', '0014_remove_adeudo_idx_adeudo_seguimiento_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adeudocomedor',
            name='idx_adeudo_comedor_pagado',
        ),
        migrations.AddField(
            model_name='adeudocomedor',
            name='adeudo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_comedor', to='pagos.adeudo'),
        ),
        migrations.RemoveField(
            model_name='adeudocomedor',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='adeudocomedor',
            name='pagado',
        ),
    ]
