# Generated by Django 6.0.1 on 2026-02-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0006_remove_adeudocomedor_idx_adeudo_comedor_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacafeteria',
            name='precio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio aplicado (se automatiiza al guardar si está vacio)', max_digits=10, null=True),
        ),
    ]
