# Generated by Django 6.0.1 on 2026-02-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0007_alter_asistenciacafeteria_precio_aplicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='precio',
        ),
    ]
