# Generated by Django 6.0.1 on 2026-02-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0008_remove_menu_precio'),
        ('pagos', '0018_adeudo_tipo_adeudo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adeudocomedor',
            name='idx_adeudo_comedor_est',
        ),
        migrations.AddField(
            model_name='asistenciacafeteria',
            name='adeudo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia_comedor', to='pagos.adeudo'),
        ),
        migrations.DeleteModel(
            name='AdeudoComedor',
        ),
    ]
