# Generated by Django 6.0.2 on 2026-02-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0009_remove_adeudocomedor_idx_adeudo_comedor_est_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusemanal',
            name='jueves_menu',
            field=models.TextField(blank=True, help_text='Menú del Jueves', null=True),
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='lunes_menu',
            field=models.TextField(blank=True, help_text='Menú del Lunes', null=True),
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='martes_menu',
            field=models.TextField(blank=True, help_text='Menú del Martes', null=True),
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='miercoles_menu',
            field=models.TextField(blank=True, help_text='Menú del Miércoles', null=True),
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='viernes_menu',
            field=models.TextField(blank=True, help_text='Menú del Viernes', null=True),
        ),
    ]
