# Generated by Django 6.0.2 on 2026-02-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0010_menusemanal_jueves_menu_menusemanal_lunes_menu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menusemanal',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Menu Semanal', 'verbose_name_plural': 'Menus Semanales'},
        ),
        migrations.RemoveField(
            model_name='menusemanal',
            name='semana_fin',
        ),
        migrations.RemoveField(
            model_name='menusemanal',
            name='semana_inicio',
        ),
    ]
