# Generated by Django 6.0.2 on 2026-02-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0011_alter_menusemanal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusemanal',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF del menu', null=True, upload_to='menus/'),
        ),
    ]
