# Generated by Django 5.1.15 on 2026-01-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_educativo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('recargo_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.conceptopagos')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(max_length=100)),
                ('comprobante', models.TextField(blank=True, null=True)),
                ('adeudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.adeudo')),
            ],
        ),
    ]
