# Generated by Django 5.1.15 on 2026-01-08 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('educational_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generation_date', models.DateField()),
                ('due_date', models.DateField()),
                ('applied_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.student')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.paymentconcept')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=100)),
                ('receipt', models.TextField(blank=True, null=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.debt')),
            ],
        ),
    ]
