# Generated by Django 6.0.1 on 2026-01-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto base antes de descuentos', max_digits=10)),
                ('nivel_educativo', models.CharField(help_text='Primaria, Secundaria, Preparatoria, Todos', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'db_table': 'conceptos_pago',
                'indexes': [models.Index(fields=['activo'], name='idx_concepto_activo')],
                'unique_together': {('nombre', 'nivel_educativo')},
            },
        ),
        migrations.CreateModel(
            name='Adeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto original del concepto', max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado por estrato', max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=2, help_text='Monto final = monto_base - descuento_aplicado', max_digits=10)),
                ('recargo_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Recargo por mora', max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='monto_final + recargo_aplicado', max_digits=10)),
                ('fecha_generacion', models.DateField(help_text='Fecha en que se generó el adeudo')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('concepto', models.ForeignKey(db_column='concepto_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.conceptopago')),
            ],
            options={
                'verbose_name': 'Adeudo',
                'verbose_name_plural': 'Adeudos',
                'db_table': 'adeudos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(help_text='Efectivo, Tarjeta, Transferencia, Cheque', max_length=100)),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de referencia bancaria', max_length=255, null=True)),
                ('ruta_recibo', models.TextField(blank=True, help_text='Ruta al comprobante de pago', null=True)),
                ('recibido_por', models.CharField(blank=True, help_text='Usuario que registró el pago', max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('adeudo', models.ForeignKey(db_column='adeudo_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.adeudo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.AddIndex(
            model_name='adeudo',
            index=models.Index(fields=['estudiante'], name='idx_adeudo_estudiante'),
        ),
        migrations.AddIndex(
            model_name='adeudo',
            index=models.Index(fields=['concepto'], name='idx_adeudo_concepto'),
        ),
        migrations.AddIndex(
            model_name='adeudo',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_adeudo_vencimiento'),
        ),
        migrations.AddIndex(
            model_name='adeudo',
            index=models.Index(fields=['estatus'], name='idx_adeudo_estatus'),
        ),
        migrations.AddIndex(
            model_name='adeudo',
            index=models.Index(fields=['estudiante', 'concepto', 'fecha_generacion'], name='idx_adeudo_seguimiento'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['adeudo'], name='idx_pago_adeudo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='idx_pago_fecha'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='idx_pago_metodo'),
        ),
    ]
