# Generated by Django 6.0.1 on 2026-01-14 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adeudo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='adeudo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='adeudo',
            name='monto_final',
        ),
        migrations.RemoveField(
            model_name='adeudo',
            name='monto_pagado',
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('vencido', 'Vencido'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_generacion',
            field=models.DateField(auto_now=True, help_text='Fecha en que se generó el adeudo'),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 14, 16, 51, 30, 938863, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
    ]
