# Generated by Django 6.0.1 on 2026-01-16 00:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_adeudo_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 16, 0, 29, 23, 946944, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='adeudo',
            field=models.OneToOneField(db_column='adeudo_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.adeudo'),
        ),
    ]
