# Generated by Django 6.0.1 on 2026-01-17 04:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_adeudo_fecha_vencimiento_alter_pago_adeudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 17, 4, 13, 5, 225502, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='adeudo',
            field=models.ForeignKey(db_column='adeudo_id', on_delete=django.db.models.deletion.CASCADE, to='pagos.adeudo'),
        ),
    ]
