# Generated by Django 6.0.1 on 2026-01-17 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_adeudo_fecha_vencimiento_alter_pago_adeudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto acumulado pagado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 17, 4, 14, 24, 675071, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
    ]
