# Generated by Django 6.0.1 on 2026-01-18 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_adeudo_monto_pagado_alter_adeudo_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio_ordinario', models.IntegerField(default=1, help_text='Dia del mes donde inicia periodo ordinario')),
                ('dia_fin_ordinario', models.IntegerField(default=10, help_text='Dia del mes donde termina periodo ordinario')),
                ('porcentaje_recargo', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de recargo por mora (ej: 10.00)', max_digits=5)),
                ('monto_fijo_recargo', models.DecimalField(decimal_places=2, default=125.0, help_text='Monto fijo adicional por recargo', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracion de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
                'db_table': 'configuracion_pago',
            },
        ),
        migrations.CreateModel(
            name='DiaNoHabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dia No Habil',
                'verbose_name_plural': 'Dias No Habiles',
                'db_table': 'dias_no_habiles',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='adeudo',
            name='generado_automaticamente',
            field=models.BooleanField(default=True, help_text='True si fue generado por el sistema'),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='justificacion_exencion',
            field=models.TextField(blank=True, help_text='Justificacion de la exencion del recargo', null=True),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='justificacion_manual',
            field=models.TextField(blank=True, help_text='Justificacion si fue creado manualmente', null=True),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='mes_correspondiente',
            field=models.DateField(blank=True, help_text='Primer dia del mes al que corresponde (ej: 2024-01-01)', null=True),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='recargo_exento',
            field=models.BooleanField(default=False, help_text='True si el recargo fue exentado'),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 18, 2, 22, 20, 965091, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
    ]
