# Generated by Django 6.0.1 on 2026-01-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_adeudo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 19, 18, 59, 35, 323358, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
    ]
