# Generated by Django 6.0.1 on 2026-01-21 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_alter_adeudo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 22, 31, 28, 267896, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
    ]
