# Generated by Django 6.0.1 on 2026-01-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_alter_adeudo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptopago',
            name='tipo_concepto',
            field=models.CharField(choices=[('colegiatura', 'Colegiatura Mensual'), ('reinscripcion', 'Reinscripción Anual'), ('inscripcion', 'Inscripción Nuevo Ingreso'), ('otro', 'Otro')], default='otro', help_text='Tipo de concepto para automatización', max_length=50),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 2, 27, 16, 39, 7, 558947, tzinfo=datetime.timezone.utc), help_text='Fecha límite de pago'),
        ),
    ]
