# Generated by Django 6.0.1 on 2026-01-30 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_conceptopago_tipo_concepto_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adeudo',
            name='idx_adeudo_seguimiento',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='idx_pago_metodo',
        ),
        migrations.RenameIndex(
            model_name='adeudo',
            new_name='idx_adeudo_eststatus',
            old_name='idx_adeudo_estatus',
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_generacion',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que se generó el adeudo'),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 3, 2), help_text='Fecha límite de pago'),
        ),
    ]
