# Generated by Django 6.0.1 on 2026-02-01 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_remove_adeudo_idx_adeudo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='adeudo_congelado',
            field=models.BooleanField(default=False, help_text='True si el adeudo está congelado por baja del estudiante'),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='dias_mora',
            field=models.IntegerField(default=0, help_text='Días transcurridos desde vencimiento'),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='recargo_fijo_aplicado',
            field=models.BooleanField(default=False, help_text='True si ya se aplicó el recargo fijo de $125 (una sola vez)'),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 3, 4), help_text='Fecha límite de pago'),
        ),
    ]
