# Generated by Django 6.0.1 on 2026-02-02 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_adeudo_adeudo_congelado_adeudo_dias_mora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2026, 3, 5), help_text='Fecha límite de pago'),
        ),
    ]
