# Generated by Django 6.0.1 on 2026-02-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_alter_adeudo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite de pago', null=True),
        ),
    ]
