# Generated by Django 6.0.1 on 2026-02-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0017_alter_adeudo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='tipo_adeudo',
            field=models.CharField(choices=[('CONCEPTO DE PAGO', 'Concepto de Pago'), ('COMEDOR', 'Asistencia Comedor')], default='CONCEPTO DE PAGO', help_text='Tipo de adeudo para seguimiento', max_length=50),
        ),
    ]
