# Generated by Django 6.0.1 on 2026-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0018_adeudo_tipo_adeudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('deposito', 'Depósito Bancario'), ('cheque', 'Cheque'), ('beca', 'Aplicación de Beca/Subsidio'), ('otro', 'Otro')], default='efectivo', help_text='Método utilizado para el pago', max_length=100),
        ),
    ]
